### ISSUE TITLE
Add discord as a option for Connections

### ISSUE THREAD

**Issue by HackedOS** [prplwtf/writea#5]
Title sums it up imo

**Comment by prplwtf** [comment]
nightmare to work with

**Comment by imlayered** [comment]
@HackedOS did you mean server or user?

**Comment by HackedOS** [comment]
i meant user, but server would also be interesting

**Comment by imlayered** [comment]
server could be pretty easy to implement (realistically could just do the same thing I did for https://github.com/prplwtf/writea/commit/33374469ef570696eaca7f6ba8568675e51ce8b7 but with discord servers)

no idea how users would work unless 2 fields were included like 
``discord_id: (user id)``
``discord_name: (username)`` and just have writea use https://discord.com/users/{discord_id} upon click

**Comment by HackedOS** [comment]
Only user id should do the job by querying discord to get username https://discord.com/developers/docs/resources/user#get-user with this api

EDIT: ignore me turns out the api needs you to be authorized to lookup users

**Comment by prplwtf** [comment]
writea is unable to send fetch requests to domain names outside of it's domain name, this is not possible to achieve.
